#!/usr/bin/env python3
"""Historical bass-heavy attempt, rejected in listening feedback.

The current cue is generated by build_discovery.py. Do not use this older script
to regenerate the project's RareDiscovery.wav.

Requires numpy. Use the PRE-change WAV as --source, not the processed output.
The source is preserved; PCM output keeps its duration, sample rate and mono layout.
All new layers are synthesized here, with no third-party game recordings.
"""

import argparse
import json
from pathlib import Path
import wave

import numpy as np


def read_pcm(path):
    with wave.open(str(path), "rb") as stream:
        if stream.getsampwidth() != 2 or stream.getnchannels() != 1:
            raise ValueError("Expected the original 16-bit mono discovery WAV")
        return (np.frombuffer(stream.readframes(stream.getnframes()), dtype="<i2")
                .astype(np.float64) / 32768), stream.getframerate()


def write_pcm(path, audio, rate):
    path.parent.mkdir(parents=True, exist_ok=True)
    pcm = np.rint(np.clip(audio, -1, 1) * 32767).astype("<i2")
    with wave.open(str(path), "wb") as stream:
        stream.setnchannels(1)
        stream.setsampwidth(2)
        stream.setframerate(rate)
        stream.writeframes(pcm.tobytes())


def shape_band(audio, rate, low, high):
    """Smooth fourth-order frequency windows; no sharp FFT-bin cutoffs."""
    size = 1 << (2 * len(audio) - 1).bit_length()
    frequency = np.fft.rfftfreq(size, 1 / rate)
    highpass = 1 - 1 / (1 + (frequency / low) ** 4)
    lowpass = 1 / (1 + (frequency / high) ** 4)
    return np.fft.irfft(np.fft.rfft(audio, size) * highpass * lowpass, size)[:len(audio)]


def envelope(t, attack, decay):
    return (1 - np.exp(-t / attack)) * np.exp(-t / decay)


def build(source, rate):
    t = np.arange(len(source)) / rate
    # Keep the recognisable high-tech signature. Leave room below it for the impact.
    signature = .78 * shape_band(source, rate, 155, 5800)
    # Falling low-mid pitch feels like a short, heavy mechanical strike, not a blast.
    phase = 2 * np.pi * (86 * t + 72 * .040 * (1 - np.exp(-t / .040)))
    thump = .52 * np.sin(phase) * envelope(t, .0025, .215)
    # Harmonics carry the weight on laptop speakers which cannot reproduce sub-bass.
    body = envelope(t, .004, .215) * (
        .205 * np.sin(2 * phase + .15)
        + .102 * np.sin(3 * phase + .5)
        + .055 * np.sin(4 * phase + .3))
    metal = np.zeros_like(source)
    for frequency, gain, decay in [(426, .105, .18), (683, .060, .115),
                                    (1097, .032, .080), (1729, .019, .048)]:
        metal += gain * np.sin(2 * np.pi * frequency * t) * envelope(t, .0017, decay)
    rng = np.random.default_rng(20261004)
    noise = shape_band(rng.normal(size=len(t)), rate, 650, 4200)
    noise /= max(np.sqrt(np.mean(noise * noise)), 1e-12)
    contact = .085 * noise * envelope(t, .0012, .024)
    # Subtle short reflections give the metal depth; no long combat-masking reverb.
    reflection = np.zeros_like(source)
    for delay, gain in [(.031, .13), (.057, .085), (.091, .045)]:
        shift = round(delay * rate)
        reflection[shift:] += (metal + contact)[:-shift] * gain
    mixed = signature + thump + body + metal + contact + reflection
    mixed = shape_band(mixed, rate, 36, 8400)
    # Gentle saturation controls transient crest factor, then reserve 1.1 dB headroom.
    mixed = np.tanh(1.32 * mixed) / 1.32
    mixed -= np.mean(mixed)
    mixed *= np.clip(t / .0015, 0, 1)
    mixed *= np.clip((len(t) / rate - t) / .075, 0, 1)
    mixed *= .88 / max(np.max(np.abs(mixed)), 1e-12)
    mixed[0] = mixed[-1] = 0
    return mixed


def measure(audio, rate, playback_volume):
    audible = audio * playback_volume
    frequencies = np.fft.rfftfreq(len(audio), 1 / rate)
    energy = np.abs(np.fft.rfft(audio)) ** 2
    db = lambda x: round(float(20 * np.log10(max(x, 1e-12))), 3)
    return {
        "duration_seconds": len(audio) / rate,
        "sample_rate": rate,
        "channels": 1,
        "pcm_peak_dbfs": db(np.max(np.abs(audio))),
        "pcm_rms_dbfs": db(np.sqrt(np.mean(audio ** 2))),
        "playback_volume": playback_volume,
        "playback_rms_dbfs": db(np.sqrt(np.mean(audible ** 2))),
        "first_300ms_playback_rms_dbfs": db(np.sqrt(np.mean(audible[:round(rate * .3)] ** 2))),
        "low_mid_80_600hz_energy_fraction": round(float(
            energy[(frequencies >= 80) & (frequencies < 600)].sum() / energy.sum()), 4),
        "dc_offset": float(np.mean(audio)),
        "full_scale_samples": int(np.sum(np.abs(audio) >= .9999)),
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--report", type=Path)
    parser.add_argument("--comparison", type=Path, help="Old at .6, silence, new at .85")
    parser.add_argument("--preview", type=Path, help="New at its in-game .85 playback level")
    args = parser.parse_args()
    if args.source.resolve() == args.output.resolve():
        raise ValueError("Keep the original source separate; processing is not idempotent")
    source, rate = read_pcm(args.source)
    refined = build(source, rate)
    write_pcm(args.output, refined, rate)
    # Measure the quantized deliverable, not just the floating-point synthesis buffer.
    delivered, _ = read_pcm(args.output)
    before, after = measure(source, rate, .6), measure(delivered, rate, .85)
    report = {"method": "Original synthesized low-mid impact + existing project signature",
              "before": before, "after": after,
              "playback_rms_increase_db": round(after["playback_rms_dbfs"] - before["playback_rms_dbfs"], 3),
              "comparison_order": "Original (0.6), 0.6 s silence, refined (0.85)"}
    assert len(delivered) == len(source)
    assert np.max(np.abs(delivered)) < .90
    assert abs(np.mean(delivered)) < .001
    assert delivered[0] == delivered[-1] == 0
    assert after["low_mid_80_600hz_energy_fraction"] > before["low_mid_80_600hz_energy_fraction"]
    assert 3 < report["playback_rms_increase_db"] < 8
    if args.report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n")
    if args.comparison:
        write_pcm(args.comparison, np.concatenate([source * .6, np.zeros(round(rate * .6)), delivered * .85]), rate)
    if args.preview:
        write_pcm(args.preview, delivered * .85, rate)
    print(json.dumps(report, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
